
#-------------------------------自定义属性， @Value("${属性名}}")--------------------------------------

#定时任务开关
job_is_excute=false

#路径规划
drivingUrl=http://124.204.76.215:21009/route/v1/driving
#历史轨迹优化,key需要根据项目自行申请
trackOpUrl=https://minedata.cn/service/lbs/track/v1/history?key=a16f4a50c820446486f6be07adc235da

#swagger开关
swagger.enable=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
swagger.title=后端模板2工程文档
swagger.version=1.0.0
swagger.author=dcc
swagger.email=dcc@com.cn
#-------------------------------自定义属性end--------------------------------------

server.port=8881
server.servlet.context-path=/service_template2
server.tomcat.max-connections=200

#postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbc-url=jdbc:postgresql://192.168.154.29:21191/service_template?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Cennavi_@2020

##其他数据源，注入otherJdbcTemplate
#other.spring.datasource.driver-class-name=org.postgresql.Driver
#other.spring.datasource.jdbc-url=jdbc:postgresql://192.168.154.29:21191/service_template?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
#other.spring.datasource.username=postgres
#other.spring.datasource.password=Cennavi_@2020

#设置上传文件大小
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

server.tomcat.uri-encoding=UTF-8
spring.messages.encoding=UTF-8

#redis
spring.redis.host=10.130.19.14
spring.redis.port=7379
spring.redis.database=0
spring.redis.password=Superman@2019
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.max-wait=-1ms
spring.redis.jedis.pool.max-idle=500
spring.redis.jedis.pool.min-idle=0
spring.redis.timeout=5000ms

#system logs
spring.audit-log.enabled=true
spring.audit-log.log-type=db

#system logs es
spring.elasticsearch.rest.uris=192.168.154.31:9200
spring.elasticsearch.rest.username=
spring.elasticsearch.rest.password=
spring.indices.show=sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*

