server.servlet.context-path=/service_template2
server.port=8881
server.tomcat.max-connections=200
spring.profiles.active=dev


#设置上传文件大小
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.uri-encoding=UTF-8
spring.messages.encoding=UTF-8

#接口文档配置
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
swagger.title=后端脚手架工程文档
swagger.version=1.0.0
swagger.author=dcc
swagger.email=dcc@com.cn



