
#-------------------------------基础配置属性， @Value("${属性名}}")--------------------------------------
#定时任务开关
job_is_excute=false

#swagger开关
swagger.enable=true

#postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbc-url=jdbc:postgresql://10.130.19.140:15432/rsrm_service_cityroad_yantai_xianchang_road?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Cennavi_@2022

##其他数据源，注入otherJdbcTemplate
#other.spring.datasource.driver-class-name=org.postgresql.Driver
#other.spring.datasource.jdbc-url=jdbc:postgresql://192.168.154.29:21191/service_template?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
#other.spring.datasource.username=postgres
#other.spring.datasource.password=Cennavi_@2020

#other.spring.datasource.driver-class-name=ru.yandex.clickhouse.ClickHouseDriver
#other.spring.datasource.jdbc-url=jdbc:clickhouse://192.168.152.53:8123,10.130.19.156:8123/tocc
#other.spring.datasource.username=cennavi
#other.spring.datasource.password=Superman@2019

#redis
spring.redis.host=10.130.19.14
spring.redis.port=7379
spring.redis.database=0
spring.redis.password=Superman@2019
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.max-wait=-1ms
spring.redis.jedis.pool.max-idle=500
spring.redis.jedis.pool.min-idle=0
spring.redis.timeout=5000ms

#system logs
spring.audit-log.enabled=true
spring.audit-log.log-type=db

#system logs es
spring.elasticsearch.rest.uris=192.168.154.31:9200
spring.elasticsearch.rest.username=elastic
spring.elasticsearch.rest.password=83399296
spring.indices.show=sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*

#-------------------------------基础配置属性属性end--------------------------------------


#-------------------------------业务配置属性， @Value("${属性名}}")-----------------------
#路径规划
drivingUrl=http://124.204.76.215:21009/route/v1/driving
#历史轨迹优化,key需要根据项目自行申请
trackOpUrl=https://minedata.cn/service/lbs/track/v1/history?key=a16f4a50c820446486f6be07adc235da

#-------------------------------业务配置属性end-----------------------------------------
